vars:
- config.yaml:obs,ref,domain,period,paths

stages:
  download/ref:
    cmd: >
      dz_download_ssh_tracks sat=${ref}
      download_dir=${paths.prepared_ref_dir}/${ref}
    outs:
    - ${paths.prepared_ref_dir}/${ref}:
        cache: false

  processing/ref:
    cmd: >
      qf_filter_merge_daily_ssh_tracks
      input_dir=${paths.prepared_ref_dir}/${ref}
      output_path=${paths.prepared_ref_dir}/${ref}.nc
      min_lon=${domain.minlon} min_lat=${domain.minlat}
      max_lon=${domain.maxlon} max_lat=${domain.maxlat}
    deps:
    - ${paths.prepared_ref_dir}/${ref}
    params:
    - method
    outs:
    - ${paths.prepared_ref_dir}/${ref}.nc:
        cache: false

  interpolate:
    cmd: >
      qf_interp_grid_on_track
      grid_path=${paths.method_outputs}/${method}.nc
      grid_var=ssh
      track_path=${paths.prepared_ref_dir}/${ref}.nc
      output_path=${paths.method_outputs}/${method}_on_c2_track.nc
    params:
    - method
    deps:
    - ${paths.method_outputs}/${method}.nc
    - ${paths.prepared_ref_dir}/${ref}.nc
    outs:
    - ${paths.method_outputs}/${method}_on_c2_track.nc:
        cache: false

  metrics/mu:
    cmd: >
      dz_alongtrack_mu
      ref_path=${paths.prepared_ref_dir}/${ref}.nc
      study_path=${paths.method_outputs}/${method}_on_c2_track.nc
      study_var=ssh
      output_path=${paths.metrics_dir}/mu_${method}.json
    params:
    - method
    deps:
    - ${paths.prepared_ref_dir}/${ref}.nc
    - ${paths.method_outputs}/${method}_on_c2_track.nc
    metrics:
    - data/metrics/mu_${method}.json:
        cache: false

  metrics/lx:
    cmd: >
      alongtrack_lambdax
      ref_path=${paths.prepared_ref_dir}/${ref}.nc
      study_path=${paths.method_outputs}/${method}_on_c2_track.nc
      study_var=ssh
      output_lambdax_path=${paths.metrics_dir}/lambdax_${method}.json
      output_psd_path=${paths.method_outputs}/${method}_psd.nc
    params:
    - method
    deps:
    - ${paths.prepared_ref_dir}/${ref}.nc
    - ${paths.method_outputs}/${method}_on_c2_track.nc
    outs:
    - ${paths.method_outputs}/${method}_psd.nc:
        cache: false
    metrics:
    - data/metrics/lambdax_${method}.json:
        cache: false

  leaderboard:
    cmd: dvc metrics show --json | python scripts/metrics.py
    deps:
    - data/metrics/lambdax_${method}.json
    - data/metrics/mu_${method}.json
