vars:
- config.yaml:obs,paths

stages:
  download/obs:
    foreach: ${obs}
    do:
      cmd: >
        dvc get -q https://github.com/quentinf00/oost-demo-ssh-dc.git
        datachallenge/data/prepared/input/${item}.nc
        -o ${paths.prepared_input_dir}/${item}.nc
      outs:
      - ${paths.prepared_input_dir}/${item}.nc:
          cache: false
  download/ref:
    cmd: >
      dvc get -q https://github.com/quentinf00/oost-demo-ssh-dc.git
      datachallenge/data/prepared/ref
      -o ${paths.prepared_ref_dir}
    outs:
    - ${paths.prepared_ref_dir}:
        cache: false
  concatenate:
    cmd: >
      qf_recipe-concat
      params.input_dir=${paths.prepared_input_dir}
      params.output_path=${paths.prepared_dir}/concatenated.nc
    deps:
    - ${paths.prepared_input_dir}
    outs:
    - ${paths.prepared_dir}/concatenated.nc:
        cache: false
  grid:
    cmd: >
      python scripts/grid.py
      +input_path=${paths.prepared_dir}/concatenated.nc
      +output_path=${paths.prepared_dir}/gridded_${resolution}.nc
      +resolution=${resolution}
    params:
    - resolution
    deps:
    - ${paths.prepared_dir}/concatenated.nc
    outs:
    - ${paths.prepared_dir}/gridded_${resolution}.nc:
        cache: false
  predict:
    cmd: >
      qf_predict_4dvarnet_starter
      input_path=${paths.prepared_dir}/gridded_${resolution}.nc
      output_dir=${paths.inference_batches}/${method}
      params.input_path=${paths.prepared_dir}/gridded_${resolution}.nc
      params.config_path=${cfg_path}
      params.ckpt_path=${ckpt_path}
    params:
    - cfg_path
    - ckpt_path
    - method
    - resolution
    deps:
    - ${paths.prepared_dir}/gridded_${resolution}.nc
    outs:
    - ${paths.inference_batches}/${method}:
        cache: false
  merge:
    cmd: >
      python scripts/merge.py
      +input_directory=${paths.inference_batches}/${method}
      +output_path=${paths.method_outputs}/${method}.nc
      +resolution=${resolution}
      hydra.run.dir=.
      hydra.output_subdir=null
      hydra/job_logging=disabled
      hydra/hydra_logging=disabled
    params:
    - method
    - resolution
    deps:
    - ${paths.inference_batches}/${method}
    outs:
    - ${paths.method_outputs}/${method}.nc:
        cache: false
  interpolate:
    cmd: >
      qf_interp_grid_on_track
      grid_path=${paths.method_outputs}/${method}.nc
      grid_var=ssh
      track_path=${paths.prepared_ref_dir}/c2.nc
      output_path=${paths.method_outputs}/${method}_on_c2_track.nc
    params:
    - method
    deps:
    - ${paths.method_outputs}/${method}.nc
    - ${paths.prepared_ref_dir}/c2.nc
    outs:
    - ${paths.method_outputs}/${method}_on_c2_track.nc:
        cache: false
  metrics/mu:
    cmd: >
      dz_alongtrack_mu
      ref_path=${paths.prepared_ref_dir}/c2.nc
      study_path=${paths.method_outputs}/${method}_on_c2_track.nc
      study_var=ssh
      output_path=${paths.metrics_dir}/mu_${method}.json
    params:
    - method
    deps:
    - ${paths.prepared_ref_dir}/c2.nc
    - ${paths.method_outputs}/${method}_on_c2_track.nc
    metrics:
    - data/metrics/mu_${method}.json:
        cache: false
  metrics/lx:
    cmd: >
      alongtrack_lambdax
      ref_path=${paths.prepared_ref_dir}/c2.nc
      study_path=${paths.method_outputs}/${method}_on_c2_track.nc
      study_var=ssh
      output_lambdax_path=${paths.metrics_dir}/lambdax_${method}.json
      output_psd_path=${paths.method_outputs}/${method}_psd.nc
    params:
    - method
    deps:
    - ${paths.prepared_ref_dir}/c2.nc
    - ${paths.method_outputs}/${method}_on_c2_track.nc
    outs:
    - ${paths.method_outputs}/${method}_psd.nc:
        cache: false
    metrics:
    - data/metrics/lambdax_${method}.json:
        cache: false
  leaderboard:
    cmd: dvc metrics show --json | python scripts/metrics.py