entrypoints: ???
hydra:
  callbacks:
    LogJobReturnCallback:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  searchpath:
    - pkg://config
    - pkg://contrib
defaults:
  - xp: ???
  - _self_

