# @package _global_

resolution: '1_8'
entrypoint: train  # 'train' or 'test'
checkpoint: null  # outputs/2023-12-07/17-58-46/comfra_1_8/checkpoints/val_mse=2.41062-epoch=145.ckpt

datamodule:
  xrds_kw:
    patch_dims: { time: 15, lat: 136, lon: 136}
    strides: { time: 1, lat: 120, lon: 120}
    domain_limits: ${domain.train}

model:
  rec_weight:
    _target_: src.utils.get_triang_time_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 7, lon: 7}
    offset: 1

defaults:
  - comfra
  - _self_
