# @package _global_

trainer:
  check_val_every_n_epoch: 1

datamodule:
  xrds_kw:
    val:
      patch_dims: {time: 15, lat: 96, lon: 96}
      strides: {time: 1, lat: 80, lon: 80}
  norm_stats:  # norm values from tgt
    train:
    - -0.005282447207719088
    - 0.21389007568359375
    val:
    - 0.043464887887239456
    - 0.22084617614746094

defaults:
  - glo12-8th
  - _self_
